default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 172.23.0.1
  port: 5432

development:
  <<: *default
  database: backend_tins_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  database: backend_tins_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['BACKEND_TINS_DATABASE_PASSWORD'] %>
